name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.12.2
homepage: https://github.com/rrousselGit/freezed

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  analyzer: ">=0.35.3 <0.41.0"
  build: ^1.5.1
  build_config: ^0.4.3
  meta: ^1.3.0-nullsafety.6
  source_gen: ^0.9.8
  freezed_annotation: '>= 0.12.0 <2.0.0'

dev_dependencies:
  json_serializable: ^3.5.0
  json_annotation: ^3.1.0
  build_test: ^1.3.0
  build_runner: ^1.10.6
  test: ^1.16.0-nullsafety.10
  matcher: ^0.12.10-nullsafety.3
  source_gen_test: ^0.1.1+1


dependency_overrides:
  freezed_annotation:
    path: ../freezed_annotation
